workflows:
  create-macOS-iso:
    environment:
      groups:
        - MEGA Credentials
    name: Create macOS ISO File
    instance_type: mac_mini_m1
    max_build_duration: 90
    scripts:
      - name: Downloading macOS Sonoma 14 Beta 1
        script: wget https://swcdn.apple.com/content/downloads/23/44/032-94352-A_DB05J15QWT/4x91v0yzolyiat5cat76ieu0h78aeu3d03/InstallAssistant.pkg
      - name: Installing macOS Sonoma 14 Beta 1 pkg File
        script: sudo installer -allowUntrusted -verboseR -pkg InstallAssistant.pkg -target /
      - name: Create macOS Sonoma 14 Beta 1 Installer ISO File
        script: |
          hdiutil create -o /tmp/Sonoma -size 14562m -volname Sonoma -layout SPUD -fs HFS+J -type UDTO -attach
          sudo /Applications/Install\ macOS\ 14\ beta.app/Contents/Resources/createinstallmedia --volume /Volumes/Sonoma --nointeraction
          hdiutil detach -force /Volumes/Install\ macOS\ 14\ beta
          mv -v /tmp/Sonoma.cdr ~/Desktop/Sonoma_14-Beta-1.iso
      - name: Installing 7zip
        script: brew install sevenzip
      - name: Compressing Sonoma_14-Beta-1.iso file
        script: 7z a -t7z -mx=9 -v4750m ~/Desktop/Sonoma_14-Beta-1/Sonoma_14-Beta-1.7z ~/Desktop/Sonoma_14-Beta-1.iso
      - name: Install Megatools
        script: brew install megatools
      - name: Upload Sonoma_14-Beta-1 folder to MEGA
        script: megatools copy --local ~/Desktop/Sonoma_14-Beta-1 --remote /Root/Shared-Files --username $MEGA_USERNAME --password "$MEGA_PASSWORD"
    artifacts:
      - ~/Desktop/Sonoma_14-Beta-1/
    publishing:
      email:
        recipients:
          - baneeishaque@gmail.com
          - baneeishaque@hotmail.com
