workflows:
  create-macOS-iso:
    name: Create macOS ISO File
    instance_type: mac_mini
    max_build_duration: 10
    scripts:
      - name: Downloading macOS Monterey Beta 10
        script: wget http://swcdn.apple.com/content/downloads/21/10/002-17762-A_GUNYNIZ0PW/witdqh4bei493fvgin01qavvy1dfhcb87w/InstallAssistant.pkg
      - name: Installing macOS Monterey Beta 10 pkg File
        script: sudo installer -allowUntrusted -verboseR -pkg InstallAssistant.pkg -target /
      - name: Create macOS Monterey Beta 10 Installer ISO File
        script: |
          hdiutil create -o /tmp/Monterey -size 16384m -volname Monterey -layout SPUD -fs HFS+J
          hdiutil attach /tmp/Monterey.dmg -noverify -mountpoint /Volumes/Monterey
          sudo /Applications/Install\ macOS\ Monterey\ beta.app/Contents/Resources/createinstallmedia --volume /Volumes/Monterey --nointeraction
          hdiutil eject -force /Volumes/Install\ macOS\ Monterey\ beta
          hdiutil convert /tmp/Monterey.dmg -format UDTO -o ~/Desktop/Monterey
          mv -v ~/Desktop/Monterey.cdr ~/Desktop/MontereyBeta10.iso         
    artifacts:
      - ~/Desktop/MontereyBeta10.iso
    publishing:
      email:
        recipients:
          - baneeishaque@hotmail.com
