workflows:
  create-macOS-iso:
    name: Create macOS ISO File
    instance_type: mac_mini
    max_build_duration: 90
    scripts:
      - name: Downloading macOS Monterey 12.3
        script: wget http://swcdn.apple.com/content/downloads/28/33/071-08758-A_9Y17AVKK4V/bg6zbc46bg162m5673fw3ubm2gowlh5388/InstallAssistant.pkg
      - name: Installing macOS Monterey 12.3 pkg File
        script: sudo installer -allowUntrusted -verboseR -pkg InstallAssistant.pkg -target /
      - name: Create macOS Monterey 12.3 Installer ISO File
        script: |
          hdiutil create -o /tmp/Monterey -size 16384m -volname Monterey -layout SPUD -fs HFS+J
          hdiutil attach /tmp/Monterey.dmg -noverify -mountpoint /Volumes/Monterey
          sudo /Applications/Install\ macOS\ Monterey.app/Contents/Resources/createinstallmedia --volume /Volumes/Monterey --nointeraction
          hdiutil eject -force /Volumes/Install\ macOS\ Monterey
          hdiutil convert /tmp/Monterey.dmg -format UDTO -o ~/Desktop/Monterey
          mv -v ~/Desktop/Monterey.cdr ~/Desktop/Monterey12.3.iso         
    artifacts:
      - ~/Desktop/Monterey12.3.iso
    publishing:
      email:
        recipients:
          - baneeishaque@gmail.com
          - baneeishaque@hotmail.com
