workflows:
  create-macOS-iso:
    name: Create macOS ISO File
    instance_type: mac_mini
    max_build_duration: 90
    scripts:
      - name: Downloading macOS Monterey 12.1
        script: wget http://swcdn.apple.com/content/downloads/06/34/002-42435-A_MA7OBDUK86/6xzypeod1xebasc92qkw2iv44e1j9pv09f/InstallAssistant.pkg
      - name: Installing macOS Monterey 12.1 pkg File
        script: sudo installer -allowUntrusted -verboseR -pkg InstallAssistant.pkg -target /
      - name: Create macOS Monterey 12.1 Installer ISO File
        script: |
          hdiutil create -o /tmp/Monterey -size 16384m -volname Monterey -layout SPUD -fs HFS+J
          hdiutil attach /tmp/Monterey.dmg -noverify -mountpoint /Volumes/Monterey
          sudo /Applications/Install\ macOS\ Monterey.app/Contents/Resources/createinstallmedia --volume /Volumes/Monterey --nointeraction
          hdiutil eject -force /Volumes/Install\ macOS\ Monterey
          hdiutil convert /tmp/Monterey.dmg -format UDTO -o ~/Desktop/Monterey
          mv -v ~/Desktop/Monterey.cdr ~/Desktop/Monterey12.1.iso         
    artifacts:
      - ~/Desktop/Monterey12.1.iso
    publishing:
      email:
        recipients:
          - baneeishaque@hotmail.com
