workflows:
  create-macOS-iso:
    name: Create macOS ISO File
    instance_type: mac_mini_m1
    max_build_duration: 90
    scripts:
      - name: Downloading macOS Ventura 13.3 Beta
        script: wget https://swcdn.apple.com/content/downloads/33/00/032-54767-A_7646O97BKU/ilkuqf54140teirbnvbct35ft5tfvunqa0/InstallAssistant.pkg
      - name: Installing macOS Ventura 13.3 Beta pkg File
        script: sudo installer -allowUntrusted -verboseR -pkg InstallAssistant.pkg -target /
      - name: Create macOS Ventura 13.3 Beta Installer ISO File
        script: |
          hdiutil create -o /tmp/Ventura -size 16384m -volname Ventura -layout SPUD -fs HFS+J
          hdiutil attach /tmp/Ventura.dmg -noverify -mountpoint /Volumes/Ventura
          sudo /Applications/Install\ macOS\ Ventura\ beta.app/Contents/Resources/createinstallmedia --volume /Volumes/Ventura --nointeraction
          hdiutil eject -force /Volumes/Install\ macOS\ Ventura\ beta
          hdiutil convert /tmp/Ventura.dmg -format UDTO -o ~/Desktop/Ventura
          mv -v ~/Desktop/Ventura.cdr ~/Desktop/Ventura_13.3-Beta.iso
      - name: Installing 7zip
        script: brew install sevenzip
      - name: Compressing Ventura_13.3-Beta.iso file
        script: 7z a -t7z -mx=9 -v4750m -sdel ~/Desktop/Ventura_13.3-Beta.7z ~/Desktop/Ventura_13.3-Beta.iso
    artifacts:
      - ~/Desktop/Ventura_13.3-Beta.*
    publishing:
      email:
        recipients:
          - baneeishaque@gmail.com
          - baneeishaque@hotmail.com
